const subjects = [
  // ===== CSE (5) =====
  {
    subjectCode: "CSE101",
    subjectTitle: "Programming Fundamentals",
    description: "Introduction to programming",
    department: "CSE",
    semester: "1",
    instructorName: "Dr. Arun",
  },
  {
    subjectCode: "CSE102",
    subjectTitle: "Data Structures",
    description: "Arrays, stacks, queues",
    department: "CSE",
    semester: "2",
    instructorName: "Dr. Arun",
  },
  {
    subjectCode: "CSE201",
    subjectTitle: "Operating Systems",
    description: "Process & memory management",
    department: "CSE",
    semester: "3",
    instructorName: "Dr. Meena",
  },
  {
    subjectCode: "CSE202",
    subjectTitle: "Database Systems",
    description: "Relational databases",
    department: "CSE",
    semester: "4",
    instructorName: "Dr. Meena",
  },
  {
    subjectCode: "CSE301",
    subjectTitle: "Web Development",
    description: "Frontend & backend basics",
    department: "CSE",
    semester: "5",
    instructorName: "Prof. Rahul",
  },

  // ===== ECE (5) =====
  {
    subjectCode: "ECE101",
    subjectTitle: "Basic Electronics",
    description: "Diodes & transistors",
    department: "ECE",
    semester: "1",
    instructorName: "Dr. Kumar",
  },
  {
    subjectCode: "ECE102",
    subjectTitle: "Circuit Theory",
    description: "Network analysis",
    department: "ECE",
    semester: "2",
    instructorName: "Dr. Kumar",
  },
  {
    subjectCode: "ECE201",
    subjectTitle: "Digital Electronics",
    description: "Logic gates & flip-flops",
    department: "ECE",
    semester: "3",
    instructorName: "Dr. Anitha",
  },
  {
    subjectCode: "ECE202",
    subjectTitle: "Signals and Systems",
    description: "Signal analysis",
    department: "ECE",
    semester: "4",
    instructorName: "Dr. Anitha",
  },
  {
    subjectCode: "ECE301",
    subjectTitle: "Communication Systems",
    description: "Analog & digital communication",
    department: "ECE",
    semester: "5",
    instructorName: "Prof. Ravi",
  },

  // ===== ME (5) =====
  {
    subjectCode: "ME101",
    subjectTitle: "Engineering Mechanics",
    description: "Statics and dynamics",
    department: "ME",
    semester: "1",
    instructorName: "Dr. Singh",
  },
  {
    subjectCode: "ME102",
    subjectTitle: "Thermodynamics",
    description: "Energy systems",
    department: "ME",
    semester: "2",
    instructorName: "Dr. Singh",
  },
  {
    subjectCode: "ME201",
    subjectTitle: "Fluid Mechanics",
    description: "Fluid behavior",
    department: "ME",
    semester: "3",
    instructorName: "Dr. Patel",
  },
  {
    subjectCode: "ME202",
    subjectTitle: "Manufacturing Processes",
    description: "Machining & casting",
    department: "ME",
    semester: "4",
    instructorName: "Dr. Patel",
  },
  {
    subjectCode: "ME301",
    subjectTitle: "Heat Transfer",
    description: "Conduction & convection",
    department: "ME",
    semester: "5",
    instructorName: "Prof. Ramesh",
  },

  // ===== CE (5) =====
  {
    subjectCode: "CE101",
    subjectTitle: "Engineering Drawing",
    description: "Technical drawing",
    department: "CE",
    semester: "1",
    instructorName: "Dr. Thomas",
  },
  {
    subjectCode: "CE102",
    subjectTitle: "Building Materials",
    description: "Construction materials",
    department: "CE",
    semester: "2",
    instructorName: "Dr. Thomas",
  },
  {
    subjectCode: "CE201",
    subjectTitle: "Structural Analysis",
    description: "Structures & loads",
    department: "CE",
    semester: "3",
    instructorName: "Dr. Joseph",
  },
  {
    subjectCode: "CE202",
    subjectTitle: "Geotechnical Engineering",
    description: "Soil mechanics",
    department: "CE",
    semester: "4",
    instructorName: "Dr. Joseph",
  },
  {
    subjectCode: "CE301",
    subjectTitle: "Transportation Engineering",
    description: "Highway design",
    department: "CE",
    semester: "5",
    instructorName: "Prof. David",
  },
];

const files = [
  // ===== CSE (5) =====
  {
    fileUniqueName: "cse_prog_notes_001",
    fileName: "Programming_Fundamentals.pdf",
    fileTitle: "Programming Fundamentals Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/cse/prog_notes.pdf",
    filePath: "/uploads/cse/prog_notes.pdf",
    fileSize: "2.4MB",
    subject: "Programming Fundamentals",
    description: "Basic programming concepts",
    instructorName: "Dr. Arun",
    department: "CSE",
    semester: "1",
    subjectId: "CSE101",
  },
  {
    fileUniqueName: "cse_ds_notes_002",
    fileName: "Data_Structures.pdf",
    fileTitle: "Data Structures Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/cse/ds_notes.pdf",
    filePath: "/uploads/cse/ds_notes.pdf",
    fileSize: "3.1MB",
    subject: "Data Structures",
    description: "Arrays, stacks, queues",
    instructorName: "Dr. Arun",
    department: "CSE",
    semester: "2",
    subjectId: "CSE102",
  },
  {
    fileUniqueName: "cse_os_qp_003",
    fileName: "OS_Question_Paper.pdf",
    fileTitle: "Operating Systems Question Paper",
    fileType: "Question paper",
    fileUrl: "https://example.com/cse/os_qp.pdf",
    filePath: "/uploads/cse/os_qp.pdf",
    fileSize: "1.2MB",
    subject: "Operating Systems",
    description: "Previous year questions",
    instructorName: "Dr. Meena",
    department: "CSE",
    semester: "3",
    subjectId: "CSE201",
  },
  {
    fileUniqueName: "cse_db_notes_004",
    fileName: "Database_Systems.pdf",
    fileTitle: "Database Systems Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/cse/db_notes.pdf",
    filePath: "/uploads/cse/db_notes.pdf",
    fileSize: "2.8MB",
    subject: "Database Systems",
    description: "SQL & normalization",
    instructorName: "Dr. Meena",
    department: "CSE",
    semester: "4",
    subjectId: "CSE202",
  },
  {
    fileUniqueName: "cse_web_assign_005",
    fileName: "Web_Dev_Assignment.pdf",
    fileTitle: "Web Development Assignment",
    fileType: "Assignment",
    fileUrl: "https://example.com/cse/web_assign.pdf",
    filePath: "/uploads/cse/web_assign.pdf",
    fileSize: "1.9MB",
    subject: "Web Development",
    description: "Frontend assignment",
    instructorName: "Prof. Rahul",
    department: "CSE",
    semester: "5",
    subjectId: "CSE301",
  },

  // ===== ECE (5) =====
  {
    fileUniqueName: "ece_basic_notes_006",
    fileName: "Basic_Electronics.pdf",
    fileTitle: "Basic Electronics Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/ece/basic_notes.pdf",
    filePath: "/uploads/ece/basic_notes.pdf",
    fileSize: "2.1MB",
    subject: "Basic Electronics",
    description: "Diodes & transistors",
    instructorName: "Dr. Kumar",
    department: "ECE",
    semester: "1",
    subjectId: "ECE101",
  },
  {
    fileUniqueName: "ece_circuit_qp_007",
    fileName: "Circuit_Theory_QP.pdf",
    fileTitle: "Circuit Theory Question Paper",
    fileType: "Question paper",
    fileUrl: "https://example.com/ece/circuit_qp.pdf",
    filePath: "/uploads/ece/circuit_qp.pdf",
    fileSize: "1.3MB",
    subject: "Circuit Theory",
    description: "Previous exam questions",
    instructorName: "Dr. Kumar",
    department: "ECE",
    semester: "2",
    subjectId: "ECE102",
  },
  {
    fileUniqueName: "ece_digital_notes_008",
    fileName: "Digital_Electronics.pdf",
    fileTitle: "Digital Electronics Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/ece/digital_notes.pdf",
    filePath: "/uploads/ece/digital_notes.pdf",
    fileSize: "2.9MB",
    subject: "Digital Electronics",
    description: "Logic gates",
    instructorName: "Dr. Anitha",
    department: "ECE",
    semester: "3",
    subjectId: "ECE201",
  },
  {
    fileUniqueName: "ece_signal_assign_009",
    fileName: "Signals_Assignment.pdf",
    fileTitle: "Signals and Systems Assignment",
    fileType: "Assignment",
    fileUrl: "https://example.com/ece/signals_assign.pdf",
    filePath: "/uploads/ece/signals_assign.pdf",
    fileSize: "1.6MB",
    subject: "Signals and Systems",
    description: "Signal problems",
    instructorName: "Dr. Anitha",
    department: "ECE",
    semester: "4",
    subjectId: "ECE202",
  },
  {
    fileUniqueName: "ece_comm_notes_010",
    fileName: "Communication_Systems.pdf",
    fileTitle: "Communication Systems Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/ece/comm_notes.pdf",
    filePath: "/uploads/ece/comm_notes.pdf",
    fileSize: "3.0MB",
    subject: "Communication Systems",
    description: "Analog & digital communication",
    instructorName: "Prof. Ravi",
    department: "ECE",
    semester: "5",
    subjectId: "ECE301",
  },

  // ===== ME (5) =====
  {
    fileUniqueName: "me_mech_notes_011",
    fileName: "Engineering_Mechanics.pdf",
    fileTitle: "Engineering Mechanics Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/me/mech_notes.pdf",
    filePath: "/uploads/me/mech_notes.pdf",
    fileSize: "2.5MB",
    subject: "Engineering Mechanics",
    description: "Statics & dynamics",
    instructorName: "Dr. Singh",
    department: "ME",
    semester: "1",
    subjectId: "ME101",
  },
  {
    fileUniqueName: "me_thermo_notes_012",
    fileName: "Thermodynamics.pdf",
    fileTitle: "Thermodynamics Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/me/thermo_notes.pdf",
    filePath: "/uploads/me/thermo_notes.pdf",
    fileSize: "2.7MB",
    subject: "Thermodynamics",
    description: "Energy systems",
    instructorName: "Dr. Singh",
    department: "ME",
    semester: "2",
    subjectId: "ME102",
  },
  {
    fileUniqueName: "me_fluid_qp_013",
    fileName: "Fluid_Mechanics_QP.pdf",
    fileTitle: "Fluid Mechanics Question Paper",
    fileType: "Question paper",
    fileUrl: "https://example.com/me/fluid_qp.pdf",
    filePath: "/uploads/me/fluid_qp.pdf",
    fileSize: "1.4MB",
    subject: "Fluid Mechanics",
    description: "Previous year paper",
    instructorName: "Dr. Patel",
    department: "ME",
    semester: "3",
    subjectId: "ME201",
  },
  {
    fileUniqueName: "me_mfg_assign_014",
    fileName: "Manufacturing_Assignment.pdf",
    fileTitle: "Manufacturing Processes Assignment",
    fileType: "Assignment",
    fileUrl: "https://example.com/me/mfg_assign.pdf",
    filePath: "/uploads/me/mfg_assign.pdf",
    fileSize: "1.8MB",
    subject: "Manufacturing Processes",
    description: "Machining problems",
    instructorName: "Dr. Patel",
    department: "ME",
    semester: "4",
    subjectId: "ME202",
  },
  {
    fileUniqueName: "me_heat_notes_015",
    fileName: "Heat_Transfer.pdf",
    fileTitle: "Heat Transfer Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/me/heat_notes.pdf",
    filePath: "/uploads/me/heat_notes.pdf",
    fileSize: "2.6MB",
    subject: "Heat Transfer",
    description: "Conduction & convection",
    instructorName: "Prof. Ramesh",
    department: "ME",
    semester: "5",
    subjectId: "ME301",
  },

  // ===== CE (5) =====
  {
    fileUniqueName: "ce_draw_notes_016",
    fileName: "Engineering_Drawing.pdf",
    fileTitle: "Engineering Drawing Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/ce/draw_notes.pdf",
    filePath: "/uploads/ce/draw_notes.pdf",
    fileSize: "2.2MB",
    subject: "Engineering Drawing",
    description: "Technical drawing",
    instructorName: "Dr. Thomas",
    department: "CE",
    semester: "1",
    subjectId: "CE101",
  },
  {
    fileUniqueName: "ce_materials_notes_017",
    fileName: "Building_Materials.pdf",
    fileTitle: "Building Materials Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/ce/materials_notes.pdf",
    filePath: "/uploads/ce/materials_notes.pdf",
    fileSize: "2.4MB",
    subject: "Building Materials",
    description: "Construction materials",
    instructorName: "Dr. Thomas",
    department: "CE",
    semester: "2",
    subjectId: "CE102",
  },
  {
    fileUniqueName: "ce_struct_qp_018",
    fileName: "Structural_Analysis_QP.pdf",
    fileTitle: "Structural Analysis Question Paper",
    fileType: "Question paper",
    fileUrl: "https://example.com/ce/struct_qp.pdf",
    filePath: "/uploads/ce/struct_qp.pdf",
    fileSize: "1.5MB",
    subject: "Structural Analysis",
    description: "Previous exam paper",
    instructorName: "Dr. Joseph",
    department: "CE",
    semester: "3",
    subjectId: "CE201",
  },
  {
    fileUniqueName: "ce_geo_assign_019",
    fileName: "Geotechnical_Assignment.pdf",
    fileTitle: "Geotechnical Engineering Assignment",
    fileType: "Assignment",
    fileUrl: "https://example.com/ce/geo_assign.pdf",
    filePath: "/uploads/ce/geo_assign.pdf",
    fileSize: "1.7MB",
    subject: "Geotechnical Engineering",
    description: "Soil mechanics problems",
    instructorName: "Dr. Joseph",
    department: "CE",
    semester: "4",
    subjectId: "CE202",
  },
  {
    fileUniqueName: "ce_transport_notes_020",
    fileName: "Transportation_Engineering.pdf",
    fileTitle: "Transportation Engineering Notes",
    fileType: "Lecture note",
    fileUrl: "https://example.com/ce/transport_notes.pdf",
    filePath: "/uploads/ce/transport_notes.pdf",
    fileSize: "2.9MB",
    subject: "Transportation Engineering",
    description: "Highway design",
    instructorName: "Prof. David",
    department: "CE",
    semester: "5",
    subjectId: "CE301",
  },
];



export  {subjects, files};